#!/system/bin/sh
#
# Enable Apps2SD

if [ -e /dev/block/mmcblk0p2 ];
then
    echo "--- enabling Apps2SD"

    # check if mmcblk0p2 isn't already mounted by other scripts
    if [ $(busybox mount|grep /dev/block/mmcblk0p2|wc -l) -eq 0 ] ; then
        # fsck the sdcard filesystem first
        e2fsck -y /dev/block/mmcblk0p2;

        # set property with exit code in case an error occurs
        setprop cm.e2fsck.errors $?;

        # mount and set perms
        busybox mount -o noatime,nodiratime -t auto /dev/block/mmcblk0p2 /system/sd;
    fi

    if [ $(busybox mount|grep /dev/block/mmcblk0p2|wc -l) -eq 1 ];
    then
        busybox chown 1000:1000 /system/sd;
        busybox chmod 771 /system/sd;

        # clean up any old symlinks, create data directories
        for i in data;
        do
            if [ -h /data/$i ];
            then
                rm /data/$i;
            fi;
            if [ ! -d /data/$i ];
            then
                mkdir /data/$i;
                busybox chown 1000:1000 /data/$i;
                busybox chmod 771 /data/$i;
            fi;
        done;

        # don't allow /data/data on sd because of upgrade issues - move it if possible
        if [ -d /system/sd/data ];
        then
            busybox cp -a /system/sd/data/* /data/data/;
            busybox rm -rf /system/sd/data;
        fi;

        # move apps from internal memory to sdcard
        for i in app app-private;
        do
            if [ ! -d /system/sd/$i ];
            then
                mkdir /system/sd/$i;
            fi

            busybox chown 1000:1000 /system/sd/$i;
            busybox chmod 771 /system/sd/$i

            if [ -d /data/$i ] && [ ! -h /data/$i ];
            then
                busybox cp -a /data/$i/* /system/sd/$i/;
                busybox rm -f /data/$i/*;
            fi;
        done;

        # symlink app dirs - they must be on the same filesystem
        for i in app app-private;
        do
            if [ -d /data/$i ] && [ ! -h /data/$i ];
            then
                busybox rm -rf /data/$i;
                busybox ln -s /system/sd/$i /data/$i;
            fi;
        done;

        # clean up old whiteouts
        for i in local misc property system tombstones data;
        do
            if [ -h /system/sd/$i ]; then rm -f /system/sd/$i; fi
        done;

        # please don't put odex files in the app directory people!
        # it causes dexopt to crash when switching builds!
        busybox rm -f /system/sd/app/*.odex

        setprop cm.a2sd.active 1;

        echo "+++ Apps2SD successfully enabled";
    else
        echo "*** Unable to mount filesystem for Apps2SD!";
    # replace symlinks with directories so we can boot without sd
    for i in app app-private;
    do
       if [ -h /data/$i ];
       then
            rm -f /data/$i;
            mkdir /data/$i;
            busybox chown 1000:1000 /data/$i;
            busybox chmod 771 /data/$i;
        fi;
    done;
fi;
fi;
